{% set name = "updater" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/updater-{{ version }}.tar.gz
  sha256: 8f540a3cf9fdfa9683509974853f73ed69acfaf82ac3f9740c62fac175a79111

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - behave ==1.2.6
    - cachier ==1.5.3
    - click ==7.1
    - loguru ==0.5.3
    - packaging ==21.3
    - plumbum ==1.7.1
    - pymongo ==3.12.1
    - python >={{ python_min }}
    - python-rex ==0.4
    - pyyaml ==5.4.1
    - requests ==2.26.0

test:
  imports:
    - updater
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/paterit/version-checker
  summary: Check and update versions of pypi packages and docker-images in your project.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
